version: '3.8'

services:
  cell-router:
    build: .
    ports:
      - "8080:8080"
      - "2112:2112"  # Add metrics port
    networks:
      - cell-network

  cell1:
    build:
      context: ./mock-cell
    environment:
      - CELL_NAME=cell1
    ports:
      - "8081:8080"
    networks:
      - cell-network

  cell2:
    build:
      context: ./mock-cell
    environment:
      - CELL_NAME=cell2
    ports:
      - "8082:8080"
    networks:
      - cell-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - cell-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - cell-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  cell-network:
    driver: bridge