global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cell-router'
    static_configs:
      - targets: ['cell-router:2112']
    metrics_path: '/metrics'
    scrape_timeout: 10s
    honor_labels: true

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
